#!/bin/bash

##############################################################################
# @Author : zadmalck <zadmalck at gmail.com>
# @Purpose: Script for Domogik device for plugin script
# @Copyleft: (C) 2015 by zadmalck
# @license: GPL(v3)
# @Coding: utf-8

# @Warning: Before using this script in Domogik is, run it in a terminal of
#           your raspbian Jessie on your Raspberry PI 2 system.
#
#           This script is licensed under the GPL. The author does not 
#           guarantee results and can not be held responsible for damage 
#           to your systems.
#
##############################################################################

# Exemple :
# parle "Bonjour docteur Chandra"

chaine="$1"
if [ "$chaine" == "" ];then
  chaine="rien a dire"
fi

/usr/bin/pico2wave -l fr-FR -w "/tmp/record.wav" "$chaine"
/usr/bin/aplay /tmp/record.wav
rm -f /tmp/record.wav

exit 0

